import { useGetSettings, useUpdateSettings, getGetSettingsQueryKey } from "@workspace/api-client-react";
import { useQueryClient } from "@tanstack/react-query";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";
import { useState, useEffect } from "react";
import { Skeleton } from "@/components/ui/skeleton";

export default function Settings() {
  const { data: settings, isLoading } = useGetSettings();
  const updateSettings = useUpdateSettings();
  const queryClient = useQueryClient();
  const { toast } = useToast();
  
  const [margin, setMargin] = useState<string>("");

  useEffect(() => {
    if (settings) {
      setMargin(settings.minimumMarginPct.toString());
    }
  }, [settings]);

  const handleSave = () => {
    const val = parseFloat(margin);
    if (isNaN(val)) return;
    
    updateSettings.mutate({ data: { minimumMarginPct: val } }, {
      onSuccess: () => {
        queryClient.invalidateQueries();
        toast({ description: "Settings saved successfully." });
      }
    });
  };

  return (
    <div className="flex-1 p-6 space-y-6 max-w-2xl mx-auto w-full">
      <div>
        <h2 className="text-2xl font-bold tracking-tight">Settings</h2>
        <p className="text-muted-foreground">Configure global application parameters.</p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Pricing Rules</CardTitle>
          <CardDescription>These rules affect the recommendations generated by the system.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          {isLoading ? (
            <Skeleton className="h-10 w-full" />
          ) : (
            <div className="space-y-2">
              <Label htmlFor="margin">Minimum Margin Percentage (%)</Label>
              <div className="flex gap-4">
                <Input 
                  id="margin" 
                  type="number" 
                  value={margin} 
                  onChange={(e) => setMargin(e.target.value)} 
                  className="max-w-[200px]"
                />
                <Button onClick={handleSave} disabled={updateSettings.isPending}>
                  Save Changes
                </Button>
              </div>
              <p className="text-xs text-muted-foreground">
                Recommendations will never suggest a price that drops the margin below this percentage relative to the kgCost.
              </p>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
