import { useState } from "react";
import { ArrowLeft, ArrowRight, BarChart3, Bell, Box, Check, ChevronDown, ChevronRight, Database, FileUp, Home, LayoutGrid, Link as LinkIcon, Menu, Search, X } from "lucide-react";
import "./_group.css";

const items = [{ label: "Catalog", icon: Box }, { label: "Price Finder", icon: Search }, { label: "Comparison", icon: BarChart3 }, { label: "Mapping Review", icon: LinkIcon }, { label: "Import Competitor", icon: FileUp }];

export default function Mobile() {
  const [drawer, setDrawer] = useState(false); const [query, setQuery] = useState("Amla"); const [filter, setFilter] = useState("All products"); const [step, setStep] = useState(1);
  return <div className="pnav-mobile-shell">
    <header className="pnav-mobile-header"><button type="button" className="pnav-mobile-control" onClick={() => setDrawer(true)} aria-label="Open app menu"><Menu size={19} /></button><button type="button" className="pnav-mobile-brand"><span className="pnav-mark"><LayoutGrid size={15} /></span><span><b>Prayag</b><small>Product Database</small></span></button><button type="button" className="pnav-mobile-control" aria-label="Notifications"><Bell size={18} /><i /></button></header>
    <div className="pnav-mobile-context"><button type="button" onClick={() => window.history.back()} aria-label="Go back"><ArrowLeft size={16} /></button><div><p>Product Database</p><strong>Import Competitor</strong></div><button type="button" aria-label="More page options"><ChevronDown size={17} /></button></div>
    <main className="pnav-mobile-content"><div className="pnav-mobile-crumb"><button type="button">Product Database</button><ChevronRight size={13} /><span>Import Competitor</span></div><div className="pnav-mobile-title"><p className="pnav-eyebrow">Import / Review flow</p><h1>Import Competitor</h1><p>Upload a competitor price list to update the comparison database.</p></div>
      <div className="pnav-mobile-flow">{["Import", "Review", "Complete"].map((label, index) => <button type="button" key={label} onClick={() => setStep(index)} className={step === index ? "is-current" : step > index ? "is-done" : ""}><span>{step > index ? <Check size={12} /> : index + 1}</span>{label}</button>)}</div>
      <div className="pnav-mobile-file"><div className="pnav-file-icon"><FileUp size={20} /></div><div><strong>Himalaya · Jan 2025</strong><p>competitor-prices-jan.csv · 248 rows</p></div><button type="button" aria-label="Remove selected file"><X size={15} /></button></div>
      <label className="pnav-search pnav-mobile-search"><Search size={16} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search products" aria-label="Search imported products" /></label><div className="pnav-mobile-filter"><label><span>Filter</span><select value={filter} onChange={e => setFilter(e.target.value)} aria-label="Filter imported products"><option>All products</option><option>Needs review</option><option>Matched</option></select><ChevronDown size={14} /></label><span>248 rows</span></div>
      <div className="pnav-mobile-review"><div className="pnav-review-head"><div><strong>Review matches</strong><p>Confirm before prices enter Comparison.</p></div><span className="pnav-pill pnav-pill-amber">14 need review</span></div>{["Amla Oil 200ml", "Neem Face Wash 100", "Ashwagandha Tabs 60"].map((name, i) => <div className="pnav-review-row" key={name}><div><small>Competitor row</small><strong>{name}</strong><span>→ PRY-00{i + 1} · {i === 2 ? "Medium" : "High"} confidence</span></div><button type="button" aria-label={`Review ${name}`}><ChevronRight size={16} /></button></div>)}</div>
      <button className="pnav-primary pnav-mobile-continue" type="button" onClick={() => setStep(Math.min(step + 1, 2))}>{step === 0 ? "Continue to review" : step === 1 ? "Complete import" : "View comparison"} <ArrowRight size={15} /></button><p className="pnav-mobile-preserve"><Database size={14} /> Search and filters are preserved when you go back.</p>
    </main>
    {drawer && <div className="pnav-drawer-backdrop" onClick={() => setDrawer(false)}><aside className="pnav-mobile-drawer" onClick={e => e.stopPropagation()}><div className="pnav-drawer-head"><strong><span className="pnav-mark"><LayoutGrid size={15} /></span> Prayag apps</strong><button type="button" onClick={() => setDrawer(false)} aria-label="Close app menu"><X size={18} /></button></div><p className="pnav-drawer-label">Product Database</p>{items.map(({ label, icon: Icon }) => <button type="button" className={label === "Import Competitor" ? "is-active" : ""} key={label} onClick={() => setDrawer(false)}><Icon size={16} />{label}{label === "Mapping Review" && <span>14</span>}</button>)}<div className="pnav-drawer-divider" /><p className="pnav-drawer-label">Other apps</p><button type="button" onClick={() => setDrawer(false)}><Home size={16} />Home</button><button type="button" onClick={() => setDrawer(false)}><BarChart3 size={16} />Competition Analysis <span>Open</span></button></aside></div>}
  </div>;
}