// Main entry point for @workspace/api-zod.
// This file is NOT generated by orval — it is manually maintained.
// orval manages ./generated/api.ts and ./index.ts (do not edit those).

export * from "./generated/api";

// AuthUser is not emitted as a zod schema; derive it from the response shape.
import type { z } from "zod";
import { GetCurrentAuthUserResponse } from "./generated/api";
export type AuthUser = NonNullable<
  z.infer<typeof GetCurrentAuthUserResponse>["user"]
>;
