// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/prayag-navigation/Current.tsx": () => import("../components/mockups/prayag-navigation/Current.tsx"),
  "./components/mockups/prayag-navigation/Mobile.tsx": () => import("../components/mockups/prayag-navigation/Mobile.tsx"),
  "./components/mockups/prayag-navigation/Unified.tsx": () => import("../components/mockups/prayag-navigation/Unified.tsx")
};
