kind = "web"
previewPath = "/"
title = "Prayag Home"
version = "1.0.0"
id = "artifacts/prayag-home"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24348

[services.development]
run = "pnpm --filter @workspace/prayag-home run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/prayag-home", "run", "build" ]
publicDir = "artifacts/prayag-home/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24348"
BASE_PATH = "/"
